import type {
  Product,
  Category,
  Order,
  Seller,
  RefundRequest,
  Notification,
  PromotionRequest,
  Banner,
  Review,
  Voucher,
  CashbackOffer,
} from "./types";

export const categories: Category[] = [
  { id: "1", name: "Electronics", icon: "Laptop", slug: "electronics" },
  { id: "2", name: "Fashion", icon: "Shirt", slug: "fashion" },
  { id: "3", name: "Home & Kitchen", icon: "Home", slug: "home-kitchen" },
  { id: "4", name: "Books", icon: "BookOpen", slug: "books" },
  { id: "5", name: "Sports", icon: "Dumbbell", slug: "sports" },
  { id: "6", name: "Beauty", icon: "Sparkles", slug: "beauty" },
  { id: "7", name: "Toys", icon: "Gamepad2", slug: "toys" },
  { id: "8", name: "Grocery", icon: "ShoppingBasket", slug: "grocery" },
];

export const products: Product[] = [
  {
    id: "p1",
    name: "Apple iPhone 15 Pro Max 256GB",
    description:
      "The most powerful iPhone ever. Features a titanium design, A17 Pro chip, and an amazing camera system.",
    price: 134900,
    originalPrice: 159900,
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&auto=format",
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&auto=format",
    ],
    category: "Electronics",
    categoryId: "1",
    sellerId: "s1",
    sellerName: "TechWorld Store",
    rating: 4.8,
    reviewCount: 2341,
    stock: 45,
    tags: ["apple", "iphone", "smartphone", "5g"],
    specifications: {
      Display: "6.7-inch Super Retina XDR",
      Chip: "A17 Pro",
      Camera: "48MP Main + 12MP Ultra Wide + 12MP 5x Telephoto",
      Battery: "4422 mAh",
      Storage: "256GB",
      OS: "iOS 17",
    },
    discount: 16,
    featured: true,
    promoted: true,
    createdAt: "2024-01-15",
  },
  {
    id: "p2",
    name: "Samsung Galaxy S24 Ultra 5G 512GB",
    description:
      "Galaxy AI is here. Embedded S Pen, 200MP camera, and titanium frame for ultimate power.",
    price: 129999,
    originalPrice: 144999,
    images: [
      "https://images.unsplash.com/photo-1707767200949-c44c5f898d0e?w=600&auto=format",
    ],
    category: "Electronics",
    categoryId: "1",
    sellerId: "s1",
    sellerName: "TechWorld Store",
    rating: 4.7,
    reviewCount: 1892,
    stock: 30,
    tags: ["samsung", "galaxy", "android", "5g"],
    specifications: {
      Display: "6.8-inch Dynamic AMOLED 2X",
      Processor: "Snapdragon 8 Gen 3",
      Camera: "200MP Main + 12MP Ultra Wide + 50MP 5x + 10MP 3x",
      Battery: "5000 mAh",
      Storage: "512GB",
      OS: "Android 14",
    },
    discount: 10,
    featured: true,
    promoted: false,
    createdAt: "2024-01-20",
  },
  {
    id: "p3",
    name: "Sony WH-1000XM5 Wireless Headphones",
    description:
      "Industry-leading noise canceling headphones with exceptional sound quality and 30-hour battery life.",
    price: 26990,
    originalPrice: 34990,
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format",
    ],
    category: "Electronics",
    categoryId: "1",
    sellerId: "s2",
    sellerName: "AudioPro India",
    rating: 4.6,
    reviewCount: 4521,
    stock: 120,
    tags: ["sony", "headphones", "wireless", "noise-canceling"],
    specifications: {
      "Driver Unit": "30mm",
      "Frequency Response": "4Hz–40,000Hz",
      Battery: "30 hours",
      "Noise Canceling": "Yes (Industry Leading)",
      Weight: "250g",
      Connectivity: "Bluetooth 5.2",
    },
    discount: 23,
    featured: true,
    promoted: true,
    createdAt: "2024-02-01",
  },
  {
    id: "p4",
    name: "Nike Air Max 270 Running Shoes",
    description:
      "Inspired by the Air Max 180 and Air Max 93, delivering all-day comfort with a large Air unit.",
    price: 8495,
    originalPrice: 11995,
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format",
    ],
    category: "Sports",
    categoryId: "5",
    sellerId: "s3",
    sellerName: "Sports Junction",
    rating: 4.4,
    reviewCount: 892,
    stock: 200,
    tags: ["nike", "shoes", "running", "air-max"],
    specifications: {
      Material: "Mesh upper with foam padding",
      Sole: "Rubber",
      Closure: "Lace-up",
      "Air Unit": "270°",
      Sizes: "UK 6-11",
    },
    discount: 29,
    featured: false,
    promoted: true,
    createdAt: "2024-02-10",
  },
  {
    id: "p5",
    name: "Instant Pot Duo 7-in-1 Electric Pressure Cooker",
    description:
      "7-in-1 multi-use programmable cooker. Pressure cooker, slow cooker, rice cooker, steamer, sauté, yogurt maker and warmer.",
    price: 6499,
    originalPrice: 9999,
    images: [
      "https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&auto=format",
    ],
    category: "Home & Kitchen",
    categoryId: "3",
    sellerId: "s4",
    sellerName: "HomeEssentials",
    rating: 4.5,
    reviewCount: 3210,
    stock: 85,
    tags: ["instant-pot", "pressure-cooker", "kitchen", "cooking"],
    specifications: {
      Capacity: "6 Quart",
      Functions: "7-in-1",
      Material: "Stainless Steel",
      Wattage: "1000W",
      Programs: "13 Smart Programs",
    },
    discount: 35,
    featured: true,
    promoted: false,
    createdAt: "2024-02-15",
  },
  {
    id: "p6",
    name: "The Alchemist - Paulo Coelho (Paperback)",
    description:
      "A mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure.",
    price: 199,
    originalPrice: 350,
    images: [
      "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&auto=format",
    ],
    category: "Books",
    categoryId: "4",
    sellerId: "s5",
    sellerName: "BookCorner",
    rating: 4.9,
    reviewCount: 12450,
    stock: 500,
    tags: ["books", "fiction", "bestseller", "paulo-coelho"],
    specifications: {
      Author: "Paulo Coelho",
      Publisher: "HarperOne",
      Pages: "208",
      Language: "English",
      "ISBN-13": "9780062315007",
    },
    discount: 43,
    featured: false,
    promoted: false,
    createdAt: "2024-01-05",
  },
  {
    id: "p7",
    name: "Lakme Absolute Matte Revolution Lip Color",
    description:
      "Highly pigmented matte lip color with a smooth application. Lasts up to 16 hours.",
    price: 449,
    originalPrice: 599,
    images: [
      "https://images.unsplash.com/photo-1586495777744-4e6232bf2f81?w=600&auto=format",
    ],
    category: "Beauty",
    categoryId: "6",
    sellerId: "s6",
    sellerName: "Glamour Hub",
    rating: 4.2,
    reviewCount: 2109,
    stock: 340,
    tags: ["lipstick", "matte", "lakme", "beauty"],
    specifications: {
      Brand: "Lakme",
      Finish: "Matte",
      "Lasting Power": "16 hours",
      "Net Weight": "3.7g",
      "Skin Type": "All",
    },
    discount: 25,
    featured: false,
    promoted: true,
    createdAt: "2024-03-01",
  },
  {
    id: "p8",
    name: "LEGO Star Wars Millennium Falcon 75257",
    description:
      "Build an icon! Recreate one of the most iconic starships from the Star Wars universe.",
    price: 14999,
    originalPrice: 17999,
    images: [
      "https://images.unsplash.com/photo-1616628188859-7a11abb6fcc9?w=600&auto=format",
    ],
    category: "Toys",
    categoryId: "7",
    sellerId: "s7",
    sellerName: "ToyKingdom",
    rating: 4.8,
    reviewCount: 784,
    stock: 25,
    tags: ["lego", "star-wars", "toys", "building-blocks"],
    specifications: {
      Pieces: "1351",
      "Age Group": "9+",
      Dimensions: "14 x 8 x 3 inches",
      Theme: "Star Wars",
      "Model Number": "75257",
    },
    discount: 17,
    featured: true,
    promoted: false,
    createdAt: "2024-02-20",
  },
  {
    id: "p9",
    name: "MacBook Pro 14-inch M3 Pro Chip",
    description:
      "MacBook Pro. The most advanced laptop chip ever in a portable powerhouse.",
    price: 199900,
    originalPrice: 219900,
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format",
    ],
    category: "Electronics",
    categoryId: "1",
    sellerId: "s1",
    sellerName: "TechWorld Store",
    rating: 4.9,
    reviewCount: 567,
    stock: 15,
    tags: ["apple", "macbook", "laptop", "m3"],
    specifications: {
      Chip: "Apple M3 Pro",
      Display: "14.2-inch Liquid Retina XDR",
      RAM: "18GB",
      Storage: "512GB SSD",
      Battery: "Up to 18 hours",
      Ports: "3x Thunderbolt 4, HDMI, SD card, MagSafe 3",
    },
    discount: 9,
    featured: true,
    promoted: true,
    createdAt: "2024-03-05",
  },
  {
    id: "p10",
    name: "Men's Slim Fit Cotton T-Shirt Pack of 3",
    description:
      "Premium quality slim fit cotton t-shirts. Comfortable for everyday wear with a modern look.",
    price: 799,
    originalPrice: 1499,
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&auto=format",
    ],
    category: "Fashion",
    categoryId: "2",
    sellerId: "s8",
    sellerName: "FashionFirst",
    rating: 4.1,
    reviewCount: 5632,
    stock: 800,
    tags: ["tshirt", "cotton", "men", "fashion"],
    specifications: {
      Material: "100% Cotton",
      Fit: "Slim Fit",
      Pack: "3 T-Shirts",
      Sizes: "S, M, L, XL, XXL",
      "Wash Care": "Machine Wash",
    },
    discount: 47,
    featured: false,
    promoted: false,
    createdAt: "2024-01-25",
  },
  {
    id: "p11",
    name: "boAt Airdopes 141 Bluetooth Earbuds",
    description:
      "True wireless earbuds with 42 hours playback, IPX4 water resistance and BEAST Mode for gaming.",
    price: 1299,
    originalPrice: 4490,
    images: [
      "https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=600&auto=format",
    ],
    category: "Electronics",
    categoryId: "1",
    sellerId: "s2",
    sellerName: "AudioPro India",
    rating: 4.0,
    reviewCount: 89234,
    stock: 1500,
    tags: ["boat", "earbuds", "tws", "bluetooth"],
    specifications: {
      Connectivity: "Bluetooth 5.3",
      "Battery Life": "42 hours (with case)",
      "Water Resistance": "IPX4",
      "Driver Size": "8mm",
      "Latency Mode": "BEAST Mode 50ms",
    },
    discount: 71,
    featured: false,
    promoted: true,
    createdAt: "2024-02-28",
  },
  {
    id: "p12",
    name: "Weber Original Kettle Premium Charcoal Grill",
    description:
      "The classic charcoal grill with a One-Touch cleaning system and glass-reinforced nylon handle.",
    price: 19999,
    originalPrice: 24999,
    images: [
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format",
    ],
    category: "Home & Kitchen",
    categoryId: "3",
    sellerId: "s4",
    sellerName: "HomeEssentials",
    rating: 4.7,
    reviewCount: 341,
    stock: 40,
    tags: ["grill", "barbecue", "outdoor", "cooking"],
    specifications: {
      "Cooking Area": "363 sq. in.",
      Material: "Porcelain-enameled",
      Diameter: "22 inches",
      Weight: "14.5 kg",
      Color: "Black",
    },
    discount: 20,
    featured: false,
    promoted: false,
    createdAt: "2024-03-10",
  },
];

export const sellers: Seller[] = [
  {
    id: "s1",
    name: "Rajesh Kumar",
    email: "rajesh@techworldstore.com",
    role: "seller",
    businessName: "TechWorld Store",
    gstin: "27AABCT3518Q1ZV",
    verified: true,
    status: "approved",
    products: ["p1", "p2", "p9"],
    rating: 4.8,
    totalSales: 12450,
    createdAt: "2023-06-15",
  },
  {
    id: "s2",
    name: "Priya Sharma",
    email: "priya@audiopro.in",
    role: "seller",
    businessName: "AudioPro India",
    gstin: "29AABCP4521Q1ZT",
    verified: true,
    status: "approved",
    products: ["p3", "p11"],
    rating: 4.6,
    totalSales: 8920,
    createdAt: "2023-08-20",
  },
  {
    id: "s3",
    name: "Amit Patel",
    email: "amit@sportsjunction.com",
    role: "seller",
    businessName: "Sports Junction",
    gstin: "24AABCP1234Q1ZS",
    verified: true,
    status: "approved",
    products: ["p4"],
    rating: 4.4,
    totalSales: 5680,
    createdAt: "2023-09-10",
  },
  {
    id: "s4",
    name: "Sunita Verma",
    email: "sunita@homeessentials.com",
    role: "seller",
    businessName: "HomeEssentials",
    verified: false,
    status: "pending",
    products: ["p5", "p12"],
    rating: 4.5,
    totalSales: 3210,
    createdAt: "2024-01-05",
  },
  {
    id: "s5",
    name: "Vikram Nair",
    email: "vikram@bookcorner.in",
    role: "seller",
    businessName: "BookCorner",
    verified: false,
    status: "pending",
    products: ["p6"],
    rating: 4.9,
    totalSales: 7800,
    createdAt: "2024-02-01",
  },
  {
    id: "s6",
    name: "Kavya Reddy",
    email: "kavya@glamourhub.in",
    role: "seller",
    businessName: "Glamour Hub",
    verified: false,
    status: "rejected",
    products: ["p7"],
    rating: 4.2,
    totalSales: 1890,
    createdAt: "2024-02-15",
  },
];

export const mockOrders: Order[] = [
  {
    id: "ORD001",
    customerId: "c1",
    customerName: "John Doe",
    items: [
      {
        product: products[0],
        quantity: 1,
      },
    ],
    total: 134900,
    status: "shipped",
    paymentStatus: "paid",
    address: {
      street: "123 MG Road",
      city: "Bangalore",
      state: "Karnataka",
      pincode: "560001",
      country: "India",
    },
    createdAt: "2024-03-10",
    estimatedDelivery: "2024-03-14",
    tracking: [
      {
        status: "placed",
        location: "Online",
        timestamp: "2024-03-10 10:30 AM",
        description: "Order placed successfully",
      },
      {
        status: "confirmed",
        location: "TechWorld Store, Mumbai",
        timestamp: "2024-03-10 02:15 PM",
        description: "Order confirmed by seller",
      },
      {
        status: "packed",
        location: "TechWorld Store, Mumbai",
        timestamp: "2024-03-11 09:00 AM",
        description: "Package has been packed and ready for pickup",
      },
      {
        status: "shipped",
        location: "Mumbai Hub",
        timestamp: "2024-03-11 04:30 PM",
        description: "Package picked up by courier partner BlueDart",
      },
    ],
  },
  {
    id: "ORD002",
    customerId: "c1",
    customerName: "John Doe",
    items: [
      { product: products[2], quantity: 1 },
      { product: products[9], quantity: 2 },
    ],
    total: 28588,
    status: "delivered",
    paymentStatus: "paid",
    address: {
      street: "123 MG Road",
      city: "Bangalore",
      state: "Karnataka",
      pincode: "560001",
      country: "India",
    },
    createdAt: "2024-03-01",
    estimatedDelivery: "2024-03-05",
    tracking: [
      {
        status: "placed",
        location: "Online",
        timestamp: "2024-03-01 09:00 AM",
        description: "Order placed successfully",
      },
      {
        status: "confirmed",
        location: "Warehouse",
        timestamp: "2024-03-01 11:00 AM",
        description: "Order confirmed",
      },
      {
        status: "packed",
        location: "Warehouse",
        timestamp: "2024-03-02 08:00 AM",
        description: "Package packed",
      },
      {
        status: "shipped",
        location: "Delhi Hub",
        timestamp: "2024-03-02 03:00 PM",
        description: "Shipped via Delhivery",
      },
      {
        status: "out_for_delivery",
        location: "Bangalore Local Hub",
        timestamp: "2024-03-05 08:00 AM",
        description: "Out for delivery with delivery agent",
      },
      {
        status: "delivered",
        location: "Home",
        timestamp: "2024-03-05 02:30 PM",
        description: "Package delivered successfully",
      },
    ],
  },
];

export const mockRefunds: RefundRequest[] = [
  {
    id: "REF001",
    orderId: "ORD002",
    customerId: "c1",
    customerName: "John Doe",
    reason: "Product received was defective - headphone left ear not working",
    status: "approved",
    amount: 26990,
    createdAt: "2024-03-06",
    updatedAt: "2024-03-07",
  },
  {
    id: "REF002",
    orderId: "ORD001",
    customerId: "c2",
    customerName: "Jane Smith",
    reason: "Wrong product delivered - received iPhone 14 instead of iPhone 15",
    status: "pending",
    amount: 134900,
    createdAt: "2024-03-12",
    updatedAt: "2024-03-12",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    userId: "c1",
    title: "Order Shipped!",
    message: "Your order #ORD001 has been shipped and is on its way.",
    type: "order",
    read: false,
    createdAt: "2024-03-11 04:30 PM",
    link: "/customer/profile/orders/ORD001",
  },
  {
    id: "n2",
    userId: "c1",
    title: "Refund Approved",
    message: "Your refund of ₹26,990 for order #ORD002 has been approved.",
    type: "refund",
    read: false,
    createdAt: "2024-03-07 11:00 AM",
    link: "/customer/profile/refunds",
  },
  {
    id: "n3",
    userId: "c1",
    title: "Flash Sale Alert!",
    message: "Big savings on Electronics! Up to 70% off - Today only.",
    type: "promotion",
    read: true,
    createdAt: "2024-03-10 08:00 AM",
    link: "/customer/products?category=electronics",
  },
  {
    id: "n4",
    userId: "c1",
    title: "Order Delivered",
    message: "Your order #ORD002 has been delivered successfully.",
    type: "order",
    read: true,
    createdAt: "2024-03-05 02:30 PM",
    link: "/customer/profile/orders/ORD002",
  },
];

export const promotionRequests: PromotionRequest[] = [
  {
    id: "pr1",
    sellerId: "s1",
    sellerName: "TechWorld Store",
    productId: "p1",
    productName: "Apple iPhone 15 Pro Max",
    type: "banner",
    budget: 50000,
    duration: 30,
    status: "approved",
    message:
      "Request for homepage banner promotion for our flagship iPhone product during the upcoming sale season.",
    createdAt: "2024-02-20",
  },
  {
    id: "pr2",
    sellerId: "s2",
    sellerName: "AudioPro India",
    productId: "p3",
    productName: "Sony WH-1000XM5",
    type: "featured",
    budget: 25000,
    duration: 15,
    status: "pending",
    message:
      "Looking to feature our Sony headphones in the featured section to increase visibility.",
    createdAt: "2024-03-08",
  },
  {
    id: "pr3",
    sellerId: "s3",
    sellerName: "Sports Junction",
    type: "boost",
    budget: 10000,
    duration: 7,
    status: "pending",
    message:
      "Boost request for Nike Air Max 270 for the upcoming sports season.",
    createdAt: "2024-03-09",
  },
  {
    id: "pr4",
    sellerId: "s1",
    sellerName: "TechWorld Store",
    productId: "p9",
    productName: "MacBook Pro 14-inch",
    type: "ad",
    budget: 75000,
    duration: 30,
    status: "rejected",
    message: "Ad placement request for MacBook Pro in search results.",
    createdAt: "2024-02-15",
  },
];

export const mockReviews: Review[] = [
  {
    id: "r1",
    productId: "p1",
    userId: "c1",
    userName: "John D.",
    rating: 5,
    comment:
      "Absolutely amazing phone! The camera quality is outstanding and the performance is butter smooth.",
    createdAt: "2024-03-05",
  },
  {
    id: "r2",
    productId: "p1",
    userId: "c2",
    userName: "Sarah K.",
    rating: 4,
    comment:
      "Great phone but expensive. The titanium build feels premium. Battery life could be better.",
    createdAt: "2024-03-08",
  },
  {
    id: "r3",
    productId: "p3",
    userId: "c3",
    userName: "Mike R.",
    rating: 5,
    comment:
      "Best noise canceling headphones I've ever used. Worth every penny!",
    createdAt: "2024-03-10",
  },
];

export const banners: Banner[] = [
  {
    id: "b1",
    title: "Up to 40% off on Electronics",
    subtitle: "Shop the latest gadgets at amazing prices",
    image:
      "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=1400&auto=format",
    link: "/customer/products?category=electronics",
    active: true,
  },
  {
    id: "b2",
    title: "Summer Fashion Sale",
    subtitle: "New arrivals in Fashion - Up to 60% off",
    image:
      "https://images.unsplash.com/photo-1445205170230-053b83016050?w=1400&auto=format",
    link: "/customer/products?category=fashion",
    active: true,
  },
  {
    id: "b3",
    title: "Home & Kitchen Essentials",
    subtitle: "Make your home beautiful with great deals",
    image:
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1400&auto=format",
    link: "/customer/products?category=home-kitchen",
    active: true,
  },
];

// ─── Vouchers ────────────────────────────────────────────────────────────────

export const mockVouchers: Voucher[] = [
  {
    id: "v1",
    code: "WELCOME200",
    type: "flat",
    value: 200,
    minOrderValue: 999,
    validUntil: "2026-12-31T23:59:59Z",
    maxUses: 1000,
    usedCount: 412,
    usedBy: [],
    description: "₹200 off on your first order above ₹999",
    active: true,
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "v2",
    code: "SAVE10",
    type: "percentage",
    value: 10,
    minOrderValue: 500,
    maxDiscount: 500,
    validUntil: "2026-09-30T23:59:59Z",
    maxUses: 5000,
    usedCount: 1234,
    usedBy: [],
    description: "10% off (up to ₹500) on orders above ₹500",
    active: true,
    createdAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "v3",
    code: "TECH15",
    type: "percentage",
    value: 15,
    minOrderValue: 2000,
    maxDiscount: 2000,
    categories: ["1"],
    validUntil: "2026-08-31T23:59:59Z",
    maxUses: 2000,
    usedCount: 567,
    usedBy: [],
    description: "15% off on Electronics (up to ₹2,000) — min order ₹2,000",
    active: true,
    createdAt: "2026-04-01T00:00:00Z",
  },
  {
    id: "v4",
    code: "FREEDEL",
    type: "free_delivery",
    value: 40,
    minOrderValue: 0,
    validUntil: "2026-07-31T23:59:59Z",
    maxUses: 10000,
    usedCount: 3456,
    usedBy: [],
    description: "Free delivery on any order — no minimum",
    active: true,
    createdAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "v5",
    code: "FASHION20",
    type: "percentage",
    value: 20,
    minOrderValue: 800,
    maxDiscount: 1000,
    categories: ["2"],
    validUntil: "2026-07-15T23:59:59Z",
    maxUses: 3000,
    usedCount: 890,
    usedBy: [],
    description: "20% off on Fashion (up to ₹1,000) — min order ₹800",
    active: true,
    createdAt: "2026-05-01T00:00:00Z",
  },
  {
    id: "v6",
    code: "FLAT500",
    type: "flat",
    value: 500,
    minOrderValue: 2500,
    validUntil: "2026-06-30T23:59:59Z",
    maxUses: 500,
    usedCount: 499,
    usedBy: [],
    description: "₹500 flat off on orders above ₹2,500 — Limited offer",
    active: false,
    createdAt: "2026-04-15T00:00:00Z",
  },
];

// ─── Cashback Offers ─────────────────────────────────────────────────────────

export const cashbackOffers: CashbackOffer[] = [
  {
    id: "cb1",
    percentage: 5,
    maxAmount: 500,
    minOrderValue: 0,
    validUntil: "2026-12-31T23:59:59Z",
    description: "5% cashback (up to ₹500) on all orders — credited after delivery",
    active: true,
  },
  {
    id: "cb2",
    percentage: 10,
    maxAmount: 1000,
    minOrderValue: 2000,
    validUntil: "2026-12-31T23:59:59Z",
    description: "10% cashback (up to ₹1,000) on Electronics orders above ₹2,000",
    categories: ["1"],
    active: true,
  },
  {
    id: "cb3",
    percentage: 8,
    maxAmount: 300,
    minOrderValue: 1000,
    validUntil: "2026-09-30T23:59:59Z",
    description: "8% cashback (up to ₹300) on Fashion & Sports orders",
    categories: ["2", "5"],
    active: true,
  },
];
